"""
Compile your repo-* skills into the brain map: <pack>/brain/brain.json (read by the session hook) and
<pack>/brain/BRAIN.md (read by people).

    crossbrain brain

Skills stay the source of truth; this is build output. Re-run after any skill changes (sync does).
With no brain pack configured, the brain goes to ~/.crossbrain/state/brain.
"""

from __future__ import annotations

import json
import re
from pathlib import Path

import hconfig as hc

EXPOSURE_RX = re.compile(r"\brotate\b|REDACTED|secret was committed|tracked in git|hardcoded .*key", re.I)
LESSON_SKILLS = ("lessons",)


def frontmatter(text: str) -> dict:
    m = re.match(r"---\s*\n(.*?)\n---", text, re.S)
    out = {}
    for line in (m.group(1) if m else "").splitlines():
        k, _, v = line.partition(":")
        if v:
            out[k.strip()] = v.strip()
    return out


def sections(text: str) -> dict[str, str]:
    out, key, buf = {}, None, []
    for line in text.splitlines():
        if line.startswith("## "):
            if key:
                out[key] = "\n".join(buf)
            key = re.sub(r"^[\d.\s]+", "", line[3:]).strip().lower()
            buf = []
        elif key:
            buf.append(line)
    if key:
        out[key] = "\n".join(buf)
    return out


def find(secs: dict[str, str], *words: str) -> str:
    for k, v in secs.items():
        if any(w in k for w in words):
            return v
    return ""


def clean(s: str, n: int = 170) -> str:
    s = re.sub(r"\s+", " ", s.replace("**", "").replace("`", "")).strip(" -:")
    return s if len(s) <= n else s[: n - 1].rstrip() + "…"


def defect_titles(body: str) -> list[str]:
    titles = [clean(l[4:], 110) for l in body.splitlines() if l.startswith("### ")]
    if not titles:
        # Classes are written as "1. **X**", "- **X**", "**1. X**" or "**A. X**" - accept all four.
        titles = [clean(m.group(1), 110) for m in
                  re.finditer(r"^\s*(?:(?:\d+\.|-)\s+)?\*\*(?:[A-Z\d]{1,2}\.\s+)?(.+?)\*\*", body, re.M)]
    return [t.rstrip(".") for t in titles][:6]


def bullets(body: str, n: int) -> list[str]:
    return [clean(re.sub(r"^\s*(?:\d+\.|-|\*)\s+", "", l)) for l in body.splitlines()
            if re.match(r"^\s*(?:\d+\.|-|\*)\s+\S", l)][:n]


def verify_cmds(body: str) -> list[str]:
    code = re.findall(r"```[a-z]*\n(.*?)```", body, re.S)
    if code:
        return [l.strip() for l in code[0].splitlines() if l.strip()][:5]
    return bullets(body, 3)


def repo_name(desc: str, skill_dir: Path) -> str:
    # "(path <projects_root>/<Repo>)" or "(path ...\GitHub\<Repo>)" - the repo folder is the last segment.
    m = re.search(r"\(path ([^)]+)\)", desc)
    if m:
        return re.split(r"[\\/]", m.group(1).strip().rstrip("\\/"))[-1]
    return skill_dir.name.removeprefix("repo-")


def repo_entry(skill_dir: Path) -> dict:
    text = (skill_dir / "SKILL.md").read_text(encoding="utf-8")
    fm, secs = frontmatter(text), sections(text)
    desc = fm.get("description", "")
    return {
        "skill": fm.get("name", skill_dir.name),
        "repo": repo_name(desc, skill_dir),
        "what": clean(desc.split(" Use whenever")[0], 220),
        "verify": verify_cmds(find(secs, "verify")),
        "defect_classes": defect_titles(find(secs, "defect")),
        "non_negotiables": bullets(find(secs, "non-negotiable"), 7),
        "exposure": bool(EXPOSURE_RX.search(text)),
    }


def build(roots: list[Path]) -> tuple[dict, str]:
    skills: dict[str, Path] = {}
    for root in roots:
        for d in sorted(root.glob("*")) if root.exists() else []:
            if (d / "SKILL.md").exists():
                skills[d.name] = d
    repos = [repo_entry(d) for n, d in sorted(skills.items()) if n.startswith("repo-")]
    lesson_skill = next((n for n in LESSON_SKILLS if n in skills), None)
    lessons = []
    if lesson_skill:
        text = (skills[lesson_skill] / "SKILL.md").read_text(encoding="utf-8")
        lessons = [clean(re.sub(r"^## \d+\.\s*", "", l), 90) for l in text.splitlines() if re.match(r"## \d+\.", l)]
    core = [n for n in sorted(skills) if not n.startswith("repo-")]
    brain = {"core_skills": core, "lessons_skill": lesson_skill, "lessons": lessons, "repos": repos}

    md = ["# Brain", "",
          "Generated by `crossbrain brain` from your skills. Do not edit by hand.", "",
          f"**{len(repos)} repos · {len(core)} other skills · {len(lessons)} cross-repo defect classes.** "
          "The `brain` skill is the entry point; in Claude Code the SessionStart hook injects the matching repo card.", ""]
    if lessons:
        md += [f"## Cross-repo defect classes (`{lesson_skill}`)", "", *[f"- {l}" for l in lessons], ""]
    md += ["## Repo map", "", "| Repo | Skill | Exposure | Top defect classes |", "|---|---|---|---|"]
    for r in repos:
        md.append(f"| {r['repo']} | `{r['skill']}` | {'⚠ rotate' if r['exposure'] else ''} | "
                  f"{'; '.join(r['defect_classes'][:3]).replace('|', '/') or '(history too thin)'} |")
    md += ["", "## Repo cards", ""]
    for r in repos:
        md += [f"### {r['repo']}", "", r["what"], "", f"- Skill: `{r['skill']}`"]
        if r["verify"]:
            md.append("- Verify: " + " · ".join(f"`{v}`" for v in r["verify"]))
        md += [f"- Non-negotiable: {n}" for n in r["non_negotiables"]] + [""]
    return brain, "\n".join(md)


def main():
    cfg = hc.load()
    brain, md = build(hc.skill_roots(cfg))
    out = hc.brain_dir(cfg)
    out.mkdir(parents=True, exist_ok=True)
    (out / "brain.json").write_text(json.dumps(brain, indent=2, ensure_ascii=False) + "\n", encoding="utf-8", newline="\n")
    (out / "BRAIN.md").write_text(md + "\n", encoding="utf-8", newline="\n")
    repos = brain["repos"]
    print(f"brain: {len(repos)} repos, {len(brain['lessons'])} lessons, "
          f"{sum(r['exposure'] for r in repos)} with exposure notes -> {out}")


if __name__ == "__main__":
    main()
